apiVersion: v1
kind: Service
metadata:
    name: argocd-server
    namespace: argocd
    labels:
        app.kubernetes.io/name: aze-dev-aks-pipe
spec:
    type: LoadBalancer
    ports:
    - name: http
      nodePort: 31832
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      nodePort: 30723
      port: 443
      protocol: TCP
      targetPort: 8080
    selector:
        app.kubernetes.io/name: argocd-server