apiVersion: apps/v1
kind: Deployment
metadata:
  name: filmagix
  namespace: app
  labels:
    app: filmagix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filmagix
  template:
    metadata:
      labels:
        app: filmagix
    spec:
      imagePullSecrets:
        - name: acr-secret1
      containers:
        - name: filmagix-container
          image: azeacrpdpipe-byexc2gcdkg7auf6.azurecr.io/filmagix:284
          ports:
            - containerPort: 8000
              name: filmagix
          envFrom:
            - configMapRef:
                name: filmagix-config
            - secretRef:
                name: filmagix-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
