name: Sync to Azure DevOps

on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Sync to Azure DevOps Repos
        env:
          AZURE_DEVOPS_USERNAME: ${{ secrets.AZURE_DEVOPS_USERNAME }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          echo "Adding or updating Azure DevOps remote..."
          if git remote get-url azure >/dev/null 2>&1; then
            git remote set-url azure https://${AZURE_DEVOPS_USERNAME}:${AZURE_DEVOPS_PAT}@dev.azure.com/0xsr1r4m/sky.xyz/_git/filmagix.git
          else
            git remote add azure https://${AZURE_DEVOPS_USERNAME}:${AZURE_DEVOPS_PAT}@dev.azure.com/0xsr1r4m/sky.xyz/_git/filmagix.git
          fi

          echo "Pushing changes to Azure DevOps..."
          git push --mirror azure
